# Generated by Django 4.2 on 2023-04-26 09:34

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='general-core-system_settings-name-label')),
                ('options', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='general-core-system_settings-options-label')),
            ],
            options={
                'verbose_name': 'general-core-system_settings-singular',
                'verbose_name_plural': 'general-core-system_settings-plural',
            },
        ),
    ]
